server:
  port: ${MANAGEMENT_SERVER_PORT:8100}
  shutdown: graceful

spring:

  application:
    name: "T.H.O.M.A.S. Management Service"

  banner:
    location: banner.txt

  main:
    allow-bean-definition-overriding: true

  threads:
    virtual:
      enabled: true

  rabbitmq:
    username: ${MANAGEMENT_RABBITMQ_USERNAME}
    password: ${MANAGEMENT_RABBITMQ_PASSWORD}
    virtual-host: '/thomas'
    addresses: ${MANAGEMENT_RABBITMQ_URL}

  cloud:

    stream:

      binders:
        rabbit:
          type: 'rabbit'

      bindings:

        organizationManagementProducer-out-0:
          binder: 'rabbit'
          destination: 'management-organization-event'
          group: 'management-organization-event'
          content-type: 'application/json'

        unitManagementProducer-out-0:
          binder: 'rabbit'
          destination: 'management-unit-event'
          group: 'management-unit-event'
          content-type: 'application/json'

        groupManagementProducer-out-0:
          binder: 'rabbit'
          destination: 'management-group-event'
          group: 'management-group-event'
          content-type: 'application/json'

        userManagementProducer-out-0:
          binder: 'rabbit'
          destination: 'management-user-event'
          group: 'management-user-event'
          content-type: 'application/json'

        emailNotificationProducer-out-0:
          binder: 'rabbit'
          destination: 'notification-email-command'
          group: 'notification-email-command'
          content-type: 'application/json'

      rabbit:

        bindings:

          organizationManagementProducer-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: '"management.organization.event"'

          unitManagementProducer-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: '"management.unit.event"'

          groupManagementProducer-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: '"management.group.event"'

          userManagementProducer-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: '"management.user.event"'

          emailNotificationProducer-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: '"notification.email.command"'

  neo4j:
    uri: ${MANAGEMENT_NEO4J_URI}
    authentication:
      username: ${MANAGEMENT_NEO4J_USERNAME}
      password: ${MANAGEMENT_NEO4J_PASSWORD}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
        exclude: autoconfig,beans,env,configprops,dump,mappings,shutdown,trace

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ} %-5p %c:%M{1}:%L - %m%n"
  level:
    root: INFO
    com.thomas: INFO
    org.neo4j.ogm: ERROR

neo4j:
  connectionUri: ${MANAGEMENT_NEO4J_URI}
  databaseName: ${MANAGEMENT_NEO4J_DATABASE}
  databaseUsername: ${MANAGEMENT_NEO4J_USERNAME}
  databasePassword: ${MANAGEMENT_NEO4J_PASSWORD}
  livenessCheck: 10000
  verifyConnection: true
  poolSize: 10
  nodePackages:
    - "com.thomas.management.data.neo4j.model.node"

bcrypt:
  costValue: 4
  pepperHash: "S#}:5=Oj`Jy[-d48"

security:
  jwt:
    issuerName: "thomas-application"
    jwtAudience: "thomas-audience"
    jwtRealm: "thomas-realm"
    jwtAlgorithm: "RSA"
#    privateKey: ${MANAGEMENT_PRIVATE_KEY}
#    publicKey: ${MANAGEMENT_PUBLIC_KEY}
    privateKey: "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJMdy8jmZmgFzf1GkAXc4i4f67WTCEbfc5xyG81eCta1d8zC1SlJn1yIQRxxhm3GIX8XBgdMHj3mEz2i2w4LlykHthqfQqWzNYUvyBU0yzrMN/lnSVDRUTB8TLA44DbU+lAaE99Ng+6ubq2IBgVEwJRtnP31W5bEzg5GuvYfKH7NAgMBAAECgYAY71/u+T46O2GioCchF0Mu1jI5YGZyvMT3q0+TC3GC2tcnWY6PpO7h3CZND+DdEkvzIo/fBMPLcgeo1sWSJ9zC0Mqi5LsdNqUqi3FYCC97nh7SojwP9Dfw7kLAA7Q+z84OHI9zpbBej6oIkpSiZgpCtMirFQU2cYdsTyPU1qnj8QJBAOanPKKi3Se0zw5lVhNG90zY1l57h8WmBMaocW4pKzqHcuU7aecNvBXv+Mv1II6N0HMmVUUhMHfu8i5TgkKNEw8CQQCjSH2TNaH4gPXosat1ySGJRX3nvTvPeUWQIRrIZ4Xux1q0BqOPHYJV7E85UZXUye7d5nvBRpSbR1Rcnk27Q+BjAkBhftNck6cTv5O+LAuEPn0OGKIUcfbkDtb5+f1oaTKCnPpt9v0+00lrpHHwFH9cgolYAx4MCIlqSLBJ8Lag1uz1AkAx9XgWlo5cTnjvHY1smIGeUpjXUtr9/AkAtGBRePtNt8lU08MvgsPiLk9/JitF1BM16dNrq4DEkeqJ/BWkenwpAkEAiT86OR+X15rMo/DbAZWOMqdyvmyn+DbJ9aveFafnHjCw7ZxgDay0xqACY0Z35GybinNd39tUxkyjr+lIoQelYA=="
    publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTHcvI5mZoBc39RpAF3OIuH+u1kwhG33OcchvNXgrWtXfMwtUpSZ9ciEEccYZtxiF/FwYHTB495hM9otsOC5cpB7Yan0KlszWFL8gVNMs6zDf5Z0lQ0VEwfEywOOA21PpQGhPfTYPurm6tiAYFRMCUbZz99VuWxM4ORrr2Hyh+zQIDAQAB"

passwordReset:
  tokenValidityMinutes: 60
  resetEmailSubject: "Resetar Senha"
  resetEmailModel: "reset-password"
  tokenValidityPattern: "dd/MM/yyyy HH:mm:ss"

token:
  accessDuration: 30
  refreshDuration: 1440

signup:
  enabled: true
  maxUnits: 10
  maxUsers: 10
  defaultRoles: ORGANIZATION_ALL,MASTER_ROLE

pageable:
  default:
    pageNumber: 1
    pageSize: 20
