refresh.token.validate-token.expired-token=Token expirado
refresh.token.validate-token.decode-error=Token inválido
refresh.token.validate-token.invalid-signature=Assinatura do token inválida
refresh.token.validate-token.invalid-issuer=Emissor do token inválido