management.signup-validation.signup-data.invalid-data=Os dados para registro são inválidos
management.signup-validation.signup-properties.signup-disabled=O registro está desabilitado

management.organization-validation.organization-data.invalid-data=Os dados da organização são inválidos
management.organization-validation.organization-data.duplicated-name=Já existe uma organização com esse nome
management.organization-validation.organization-data.duplicated-registration=Já existe uma organização com esse número de registro
management.organization-search.not-found.error-message=Organização não encontrada com o id {0}

management.unit-validation.unit-data.invalid-data=Os dados da unidade são inválidos
management.unit-validation.unit-data.duplicated-name=Já existe uma unidade com esse nome
management.unit-validation.unit-data.duplicated-document=Já existe uma unidade com esse número de documento
management.unit-validation.organization-data.max-unit=A Organização atingiu o limite de unidades
management.unit-search.not-found.error-message=Unidade não encontrada com o id {0}

management.user-validation.user-data.invalid-data=Os dados do usuário são inválidos
management.user-validation.user-data.duplicated-document=Já existe um usuário com esse documento na organização
management.user-validation.user-data.duplicated-email=Já existe um usuário com esse e-mail
management.user-validation.organization-data.max-user=A Organização atingiu o limite de usuários
management.user-validation.group-data.not-found=Os grupos com os ids {0} não foram encontrados
management.user-validation.unit-data.not-found=As unidades com os ids {0} não foram encontradas
management.user-validation.user-data.invalid-password=A senha deve conter pelo menos 8 caracteres entre maiúsculos, minusculos, números e simbolos
management.user-search.not-found.error-message=Usuário não encontrado com o id {0}

management.reset-password.reset-token.invalid-token=Token inválido
management.reset-password.reset-token.expired-token=Token expirado

management.group-validation.group-data.invalid-data=Os dados do grupo são inválidos
management.group-validation.group-data.duplicated-name=Já existe um grupo com esse nome
management.group-validation.unit-data.not-found=As unidades com os ids {0} não foram encontradas
management.group-search.not-found.error-message=Grupo não encontrado com o id {0}

management.authentication-login.credential-data.invalid-credentials=Usuário ou senha inválidos
management.authentication-login.organization-data.inactive-organization=Organização inativa
management.authentication-login.user-data.inactive-user=Usuário inativo
management.authentication-refresh.refresh-token.invalid-token=Refresh token inválido