management.signup-validation.signup-data.invalid-data=Os dados para registro são inválidos
management.signup-validation.signup-properties.signup-disabled=O registro está desabilitado

management.organization-validation.organization-data.duplicated-name=Já existe uma organização com esse nome
management.organization-validation.organization-data.duplicated-registration=Já existe uma organização com esse número de registro

management.user-validation.user-data.duplicated-document=Já existe um usuário com esse documento na organização
management.user-validation.user-data.duplicated-email=Já existe um usuário com esse e-mail