management.signup-validation.signup-data.invalid-data=Os dados para registro são inválidos
management.signup-validation.signup-properties.signup-disabled=O registro está desabilitado

management.organization-validation.organization-data.invalid-data=Os dados da organização são inválidos
management.organization-validation.organization-data.duplicated-name=Já existe uma organização com esse nome
management.organization-validation.organization-data.duplicated-registration=Já existe uma organização com esse número de registro
management.organization-search.not-found.error-message=Organização não encontrada com o id {0}

management.unit-validation.unit-data.invalid-data=Os dados da unidade são inválidos
management.unit-validation.unit-data.duplicated-name=Já existe uma unidade com esse nome
management.unit-validation.unit-data.duplicated-document=Já existe uma unidade com esse número de documento
management.unit-validation.organization-data.max-unit=A Organização atingiu o limite de unidades
management.unit-search.not-found.error-message=Unidade não encontrada com o id {0}

management.user-validation.user-data.duplicated-document=Já existe um usuário com esse documento na organização
management.user-validation.user-data.duplicated-email=Já existe um usuário com esse e-mail